### ISSUE TITLE
Add Sponsors section

### ISSUE THREAD

**Issue by MrSunshyne** [Front-End-Coders-Mauritius/meetup-fec-nuxt#5]
Add a section to feature sponsors of the Front-end Coders meetup

**Comment by kushul** [comment]
![logoPlaceholder](https://user-images.githubusercontent.com/40826382/172043933-a6a774dc-9192-4704-92f3-46132c39503e.png)

Use this image as placeholder

**Comment by MrSunshyne** [comment]
https://github.com/Front-End-Coders-Mauritius/meetup-fec-nuxt/commit/4933e5b57666332221acbff7b31da1ba1bd8923d

**Comment by mahima98** [comment]
![sponsorSection](https://user-images.githubusercontent.com/45752743/172047451-d5ff4314-e30c-462b-9f00-92ceaa277d30.png)
sponsor section Added!
