### ISSUE TITLE
Add Event RSVP button

### ISSUE THREAD

**Issue by MrSunshyne** [Front-End-Coders-Mauritius/meetup-fec-nuxt#7]
We can make RSVPs with Typeform perhaps...?

I added a field in the api, `rsvplink`, accessible for all events. 

Add a button to RSVP if a link is present on each event.

**Comment by kushul** [comment]
Hi @MrSunshyne 

Button has been added when link is present.

**Comment by MrSunshyne** [comment]
Okay results are coming in

![image](https://user-images.githubusercontent.com/1721611/172044105-ddae89a0-377d-4c2b-82b8-11770bbd5118.png)


![image](https://user-images.githubusercontent.com/1721611/172044103-b6bc10bd-2bba-44e7-bc5b-906714f073f3.png)
